dist: trusty
sudo: required

language: cpp

services:
  - docker

before_install:
        - docker pull financialmaporg/backend:latest

script:
        - docker run -v "$PWD/backend:/app:rw" financial/backend:0.1 /bin/bash -c "ls -al"
